# Generated by Django 4.0.4 on 2022-05-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default='web', max_length=20),
            preserve_default=False,
        ),
    ]
