# Generated by Django 4.0.4 on 2022-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0003_skills_skills_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('project', models.CharField(max_length=2000)),
            ],
        ),
    ]
