# Generated by Django 4.0.4 on 2022-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0005_rename_project_contactform_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=300),
        ),
    ]
