# Generated by Django 4.0.4 on 2022-07-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0006_alter_about_description_alter_about_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='career',
        ),
    ]
