# Generated by Django 4.0.4 on 2022-07-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0007_remove_about_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills_level',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='Demo', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=50),
        ),
    ]
