# Generated by Django 4.0.4 on 2022-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lazy', '0008_remove_skills_skills_level_portfolio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=200),
        ),
    ]
